# Site wide configuration

title: "wsg"
locale: en_US
description: the personal weblog of william s godfrey
logo: #favicon-32x32.png
search: true
url: http://williamsgodfrey.com

# Resume settings
resume_avatar:                  "false"
resume_name:                    "William S Godfrey"
resume_title:                   "Structural Analyst"
resume_contact_email:
  "will@williamsgodfrey.com"
  
# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  enable_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: William S Godfrey
  avatar: me.png
  email: will@williamsgodfrey.com
  disqus-shortname: williamsgodfrey
  twitter: williamsgodfrey
  facebook: williamsgodfrey
  github: williamsgodfrey
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: williamsgodfrey
  instagram: w.godfrey
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: williamsgodfrey
    analytics: UA-22235342-1
    verify: 0rpDl4v-FXLHMmi32wB1aNyv77WU8qQ47mLv3RNIZms
    ad-client:
    ad-slot:
  bing-verify:
